stages:
  - build
  - docker

variables:
  SERVER_IMAGE_NAME: "mafil-reg-server"
  WEB_IMAGE_NAME: "mafil-reg-web"

#-----------------------------------------------------------------------------------------------------------------------
# Backend
#-----------------------------------------------------------------------------------------------------------------------
backend-build:
  stage: build
  image: node:20
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel" || $CI_COMMIT_BRANCH == "main"'
      changes:
        - '.gitlab-ci.yml'
        - 'package.json'
        - 'tsconfig.base.json'
        - '.eslintrc.js'
        - 'backend/**/*'
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install --frozen-lockfile    # Install common repo dependencies
    - cd backend
    - pnpm install --frozen-lockfile    # Install backend dependencies
    - pnpm exec prisma generate         # Generate Prisma types
    - pnpm lint                         # Lint the code
    - pnpm build                        # Build the backend
    - pnpm test                         # Run the tests
  artifacts:
    paths:
      - backend/dist                    # Include build artifacts if needed
    expire_in: 1 day

backend-create-devel-docker-image:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  needs:
    - backend-build
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel"'
      changes:
        - '.gitlab-ci.yml'
        - 'package.json'
        - 'tsconfig.base.json'
        - 'backend/**/*'
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --build-arg "COMMIT_HASH=${CI_COMMIT_SHORT_SHA}"
      --build-arg "COMMIT_DATE=${CI_COMMIT_TIMESTAMP}"
      --destination "${CI_REGISTRY_IMAGE}/${SERVER_IMAGE_NAME}:${CI_COMMIT_BRANCH}"

backend-create-latest-docker-image:
  stage: docker
  needs:
    - backend-create-devel-docker-image
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker pull "${CI_REGISTRY_IMAGE}/${SERVER_IMAGE_NAME}:devel"
    - docker tag "${CI_REGISTRY_IMAGE}/${SERVER_IMAGE_NAME}:devel" "${CI_REGISTRY_IMAGE}/${SERVER_IMAGE_NAME}:latest"
    - docker push "${CI_REGISTRY_IMAGE}/${SERVER_IMAGE_NAME}:latest"

#-----------------------------------------------------------------------------------------------------------------------
# Frontend
#-----------------------------------------------------------------------------------------------------------------------
frontend-build:
  stage: build
  image: node:20
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel" || $CI_COMMIT_BRANCH == "main"'
      changes:
        - '.gitlab-ci.yml'
        - 'package.json'
        - 'tsconfig.base.json'
        - '.eslintrc.js'
        - 'frontend/**/*'
  before_script:
    - npm install -g pnpm
  script:
    - pnpm install --frozen-lockfile    # Install common repo dependencies
    - cd frontend
    - pnpm install --frozen-lockfile    # Install frontend dependencies
    - pnpm lint                         # Lint the code
    - pnpm build                        # Build the frontend
    - pnpm test                         # Run the tests
  artifacts:
    paths:
      - frontend/dist                   # Include build artifacts if needed
    expire_in: 1 day

frontend-create-devel-docker-image:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  needs:
    - frontend-build
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel"'
      changes:
        - '.gitlab-ci.yml'
        - 'package.json'
        - 'tsconfig.base.json'
        - 'frontend/**/*'
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --build-arg "COMMIT_HASH=${CI_COMMIT_SHORT_SHA}"
      --build-arg "COMMIT_DATE=${CI_COMMIT_TIMESTAMP}"
      --destination "${CI_REGISTRY_IMAGE}/${WEB_IMAGE_NAME}:${CI_COMMIT_BRANCH}"

frontend-create-latest-docker-image:
  stage: docker
  needs:
    - frontend-create-devel-docker-image
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker pull "${CI_REGISTRY_IMAGE}/${WEB_IMAGE_NAME}:devel"
    - docker tag "${CI_REGISTRY_IMAGE}/${WEB_IMAGE_NAME}:devel" "${CI_REGISTRY_IMAGE}/${WEB_IMAGE_NAME}:latest"
    - docker push "${CI_REGISTRY_IMAGE}/${WEB_IMAGE_NAME}:latest"
