services:
  postgres:
    container_name: postgres
    image: postgres:alpine3.17
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend-network
    volumes:
      - ./backend/database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    networks:
      - backend-network
    environment:
      ADMINER_DESIGN: nette
    restart: unless-stopped
    depends_on:
      - postgres

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    command: pnpm start:migrate:dev
    volumes:
      - ./server-config.yaml:/usr/src/app/backend/config.yaml:ro
      # Changes in host's ./backend directory will be propagated to the container
      # This will also let us add packages during development without rebuilding the image
      # - We then need to install added packages (run 'pnpm add <pkg>') inside the container in the folder '/usr/src/app/backend'
      - ./backend:/usr/src/app/backend
      # This prevents our host files from overriding container's node_modules
      # – Some packages may be platform specific so we always need to run 'pnpm add <pkg>' in the container when new package is added
      - exclude-server:/usr/src/app/backend/node_modules/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - backend-network
    environment:
      - NODE_ENV=development
      - PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    depends_on:
      - postgres

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development
    command: pnpm dev
    volumes:
      - ./web-config.json:/usr/src/app/frontend/public/config.json:ro
      # Changes in host's ./frontend directory will be propagated to the container
      # This will also let us add packages during development without rebuilding the image
      # - We then need to install added packages (run 'pnpm add <pkg>') inside the container in the folder '/usr/src/app/frontend'
      - ./frontend:/usr/src/app/frontend
      # This prevents our host files from overriding container's node_modules
      # – Some packages may be platform specific so we always need to run 'pnpm add <pkg>' in the container when new package is added
      - exclude-web:/usr/src/app/frontend/node_modules/
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    networks:
      - backend-network
      - frontend-network
    environment:
      - NODE_ENV=development
      - PORT=${WEB_PORT}
    restart: unless-stopped
    depends_on:
      - server

networks:
  backend-network:
  frontend-network:

volumes:
  database-storage:
  exclude-server:
  exclude-web:
