version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine3.17
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend-network
    volumes:
      - ./database-storage:/var/lib/postgresql/data
    environment:
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    networks:
      - backend-network
    environment:
      TZ: ${TIMEZONE}
      ADMINER_DESIGN: rmsoft
    restart: unless-stopped
    depends_on:
      - postgres

  server:
    container_name: server
    image: ghcr.io/lukas-kratochvil/mafil-psq-server:devel
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - backend-network
    environment:
      - NODE_ENV=production
      - TZ=${TIMEZONE}
      - PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - THROTTLE_TTL=${THROTTLE_TTL}
      - THROTTLE_LIMIT=${THROTTLE_LIMIT}
      - API_KEY_FOR_WEB=${SERVER_API_KEY_FOR_WEB}
      - PDF_OPERATOR_LANGUAGE_CODE=${PDF_OPERATOR_LANGUAGE_CODE}
      # - WEB_DOMAIN=${WEB_DOMAIN}
    restart: unless-stopped
    depends_on:
      - postgres

  web:
    container_name: web
    image: ghcr.io/lukas-kratochvil/mafil-psq-web:devel
    ports:
      - 80:80
      - 443:443
    networks:
      - backend-network
      - frontend-network
    environment:
      - NODE_ENV=production
      - TZ=${TIMEZONE}
      - WEB_DOMAIN=${WEB_DOMAIN}
      - SERVER_PORT=${SERVER_PORT}
      - ADMINER_PORT=${ADMINER_PORT}
      - SERVER_API_KEY=${SERVER_API_KEY_FOR_WEB}
      - MAFILDB_API_URL=${MAFILDB_API_URL}
    volumes:
      - ./secrets.json:/usr/share/nginx/html/assets/secrets.json
    restart: unless-stopped
    depends_on:
      - server

networks:
  backend-network:
  frontend-network:

volumes:
  database-storage:
