version: '3.8'

services:
  server:
    image: mafil-psq-server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    command: npm run start:dev
    restart: always

  web:
    image: mafil-psq-web
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: development
    command: npm run dev
    restart: always
