@startuml ProbandSafetyQuestionnaire

' avoid problems with angled crows feet
skinparam linetype ortho

entity Operator {
  * id: string <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * name: string
  * surname: string
  * uco: string
  * email: string
  * role: OperatorRole
  * isValid: boolean
}

enum OperatorRole {
  MR
  MR_HIGH_PERM
}

entity VisitForm {
  * id: string <<UUID>>
  ---
  * probandLanguageId: string <<FK>>
  * genderId: string <<FK>>
  * handednessId: string <<FK>>
  * nativeLanguageId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * state: VisitFormState
  * name: string
  * surname: string
  * personalId: string
  * birthdate: Date
  * heightCm: float
  * weightKg: float
  * visualCorrectionDioptre: float
  email: string
  phone: string
}

enum VisitFormState {
  NEW
  IN_APPROVAL
  SENT_TO_MAFILDB
  DELETED
}

entity AdditionalVisitFormInfo {
  * id: string <<UUID>>
  ---
  * visitFormId: string <<FK>>
  * operatorId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * projectId: string <<UUID>>
  * projectAcronym: string
  * deviceId: string <<UUID>>
  * deviceName: string
  * measuredAt: Date
  * finalizedAt: Date
}

enum AnswerOption {
  YES
  NO
}

entity Answer {
  * id: string <<UUID>>
  ---
  * visitFormId: string <<FK>>
  * questionId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * answer: AnswerOption
  comment: string
}

entity Question {
  * id: string <<UUID>>
  ---
  previousQuestionId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * partNumber: int
  * mustBeApproved: boolean
  * isValid: boolean
}

entity QuestionTranslation {
  * id: string <<UUID>>
  ---
  * questionId: string <<FK>>
  * languageId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: string
}

entity GenderHiddenQuestion {
  * id: string <<UUID>>
  ---
  * genderCode: string <<FK>>
  * questionId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
}

entity Gender {
  * id: string <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * code: string
}

entity GenderTranslation {
  * id: string <<UUID>>
  ---
  * genderId: string <<FK>>
  * languageId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: string
}

entity Handedness {
  * id: string <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * code: string
}

entity HandednessTranslation {
  * id: string <<UUID>>
  ---
  * handednessId: string <<FK>>
  * languageId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: string
}

entity NativeLanguage {
  * id: string <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * code: string
  order: int
}

entity NativeLanguageTranslation {
  * id: string <<UUID>>
  ---
  * nativeLanguageId: string <<FK>>
  * languageId: string <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: string
}

entity Language {
  * id: string <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * code: string
  * name: string
}

Operator }o..|| OperatorRole
Operator ||..o{ AdditionalVisitFormInfo : finalized by
VisitForm }o..|| VisitFormState
VisitForm ||..o| AdditionalVisitFormInfo
VisitForm ||..|{ Answer
VisitForm }o..|| Language
VisitForm }o..|| Gender
VisitForm }o..|| Handedness
VisitForm }o..|| NativeLanguage
Answer }o..|| Question
Answer }o..|| AnswerOption
Question |o..|| Question
Question ||..|{ QuestionTranslation
QuestionTranslation }o..|| Language
GenderHiddenQuestion }o..|| Gender
GenderHiddenQuestion }o..|| Question
Gender ||..|{ GenderTranslation
GenderTranslation }o..|| Language
Handedness ||..|{ HandednessTranslation
HandednessTranslation }o..|| Language
NativeLanguage ||..|{ NativeLanguageTranslation
NativeLanguageTranslation }o..|| Language

@enduml
