@startuml ERD

' avoid problems with angled crows feet
skinparam linetype ortho

entity Operator {
  * id: UUID <<generated>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * name: string
  * surname: string
  * uco: string
  * email: string
  * role: OperatorRole
  * isValid: boolean
}

enum OperatorRole {
  MR
  MR_HIGH_PERM
}

entity VisitForm {
  * id: UUID <<generated>>
  ---
  * probandLanguageId: UUID <<FK>>
  * genderId: UUID <<FK>>
  * handednessId: UUID <<FK>>
  * nativeLanguageId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * state: VisitFormState
  sentToMafilDbAt: date
  * name: string
  * surname: string
  * personalId: string
  * birthdate: date
  * heightCm: float
  * weightKg: float
  * visualCorrectionDioptre: float
  email: string
  phone: string
}

enum VisitFormState {
  NEW
  IN_APPROVAL
  SENT_TO_MAFILDB
  PDF_GENERATED
  DELETED
}

entity AdditionalVisitFormInfo {
  * id: UUID <<generated>>
  ---
  * visitFormId: UUID <<FK>>
  * operatorId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * projectId: UUID
  * projectAcronym: string
  * deviceId: UUID
  * deviceName: string
  * measuredAt: date
  * finalizedAt: date
}

enum AnswerOption {
  YES
  NO
}

entity Answer {
  * id: UUID <<generated>>
  ---
  * visitFormId: UUID <<FK>>
  * questionId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * answer: AnswerOption
  comment: string
}

entity Question {
  * id: UUID <<generated>>
  ---
  previousQuestionId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * partNumber: int
  * mustBeApproved: boolean
  * order: int
  * isValid: boolean
}

entity QuestionTranslation {
  * id: UUID <<generated>>
  ---
  * questionId: UUID <<FK>>
  * languageId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * text: string
}

entity GenderHiddenQuestion {
  * id: UUID <<generated>>
  ---
  * genderCode: string <<FK>>
  * questionId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
}

entity Gender {
  * id: UUID <<generated>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * code: string
  * order: int
}

entity GenderTranslation {
  * id: UUID <<generated>>
  ---
  * genderId: UUID <<FK>>
  * languageId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * text: string
}

entity Handedness {
  * id: UUID <<generated>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * code: string
  * order: int
}

entity HandednessTranslation {
  * id: UUID <<generated>>
  ---
  * handednessId: UUID <<FK>>
  * languageId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * text: string
}

entity NativeLanguage {
  * id: UUID <<generated>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * code: string
  order: int
}

entity NativeLanguageTranslation {
  * id: UUID <<generated>>
  ---
  * nativeLanguageId: UUID <<FK>>
  * languageId: UUID <<FK>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * text: string
}

entity Language {
  * id: UUID <<generated>>
  ---
  * createdAt: date
  * modifiedAt: date
  deletedAt: date
  ---
  * code: string
  * name: string
}

Operator }o.|| OperatorRole
Operator ||.o{ AdditionalVisitFormInfo : finalized by
AdditionalVisitFormInfo |o..|| VisitForm
VisitFormState ||.o{ VisitForm
VisitForm ||..|{ Answer
VisitForm }o..|| Language
VisitForm }o..|| Gender
VisitForm }o...|| Handedness
VisitForm }o...|| NativeLanguage
Answer }o..|| Question
AnswerOption ||.o{ Answer
Question |o..|| Question
Question ||..|{ QuestionTranslation
QuestionTranslation }o..|| Language
GenderHiddenQuestion }o..|| Gender
GenderHiddenQuestion }o..|| Question
Gender ||..|{ GenderTranslation
GenderTranslation }o..|| Language
Handedness ||..|{ HandednessTranslation
HandednessTranslation }o..|| Language
NativeLanguage ||..|{ NativeLanguageTranslation
NativeLanguageTranslation }o..|| Language

@enduml
