@startuml ProbandSafetyQuestionnaire

entity Operator {
  * id: <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * name: String
  * surname: String
  * uco: String
  * email: String
  * role: OperatorRole
  * isValid: Boolean
}

enum OperatorRole {
  MR
  MR_HIGH_PERM
}

entity VisitForm {
  * id: <<UUID>>
  * probandInfoId: <<FK>>
  * probandLanguageId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * state: VisitFormState
  visitId: String
  pdf: Bytes
}

enum VisitFormState {
  NEW
  IN_APPROVAL
  APPROVED
  DISAPPROVED
  FOR_SIGNATURE
  SIGNED
  DELETED
}

entity AdditionalVisitFormInfo {
  * id: <<UUID>>
  * visitFormId: <<FK>>
  * operatorId: <<FK>>
  approverId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * projectId: <<UUID>>
  * projectAcronym: String
  * deviceId: <<UUID>>
  * deviceName: String
  * isPhantom: Boolean
  * measuredAt: Date
  * finalizedAt: Date
  approvedAt: Date
}

entity ProbandInfo {
  * id: <<UUID>>
  * genderId: <<FK>>
  * handednessId: <<FK>>
  * nativeLanguageId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * name: String
  * surname: String
  * personalId: String
  * birthdate: Date
  * heightCm: Float
  * weightKg: Float
  * visualCorrectionDioptre: Float
  email: String
  phone: String
}

entity Answer {
  * id: <<UUID>>
  * visitFormId: <<FK>>
  * questionId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * answer: String
  comment: String
}

entity Question {
  * id: <<UUID>>
  previousQuestionId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * partNumber: Int
  * mustBeApproved: Boolean
  * isValid: Boolean
}

entity QuestionTranslation {
  * id: <<UUID>>
  * questionId: <<FK>>
  * languageId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: String
}

entity GenderHiddenQuestion {
  * id: <<UUID>>
  * genderCode: <<FK>>
  * questionId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
}

entity Gender {
  * id: <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * code: String
}

entity GenderTranslation {
  * id: <<UUID>>
  * genderId: <<FK>>
  * languageId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: String
}

entity Handedness {
  * id: <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
}

entity HandednessTranslation {
  * id: <<UUID>>
  * handednessId: <<FK>>
  * languageId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: String
}

entity NativeLanguage {
  * id: <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  order: Int
}

entity NativeLanguageTranslation {
  * id: <<UUID>>
  * nativeLanguageId: <<FK>>
  * languageId: <<FK>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * text: String
}

entity Language {
  * id: <<UUID>>
  ---
  * createdAt: Date
  * modifiedAt: Date
  deletedAt: Date
  ---
  * code: String
  * name: String
}

Operator }o..|| OperatorRole
Operator ||..o{ AdditionalVisitFormInfo : finalized by
Operator |o..o{ AdditionalVisitFormInfo : approved by
VisitForm }o..|| VisitFormState
VisitForm ||..o| AdditionalVisitFormInfo
VisitForm }|..|| ProbandInfo
VisitForm ||..|{ Answer
VisitForm }o..|| Language
Answer }o..|| Question
Question |o..|| Question
Question ||..|{ QuestionTranslation
QuestionTranslation }o..|| Language
ProbandInfo }o..|| Gender
ProbandInfo }o..|| Handedness
ProbandInfo }o..|| NativeLanguage
GenderHiddenQuestion }o..|| Gender
GenderHiddenQuestion }o..|| Question
Gender ||..|{ GenderTranslation
GenderTranslation }o..|| Language
Handedness ||..|{ HandednessTranslation
HandednessTranslation }o..|| Language
NativeLanguage ||..|{ NativeLanguageTranslation
NativeLanguageTranslation }o..|| Language

@enduml
