name: CI - backend

on:
  push:
    branches: [ "devel", "main" ]
    paths:
      - '.github/workflows/ci-backend.yml'
      - 'package.json'
      - 'tsconfig.base.json'
      - '.eslintrc.js'
      - 'backend/**'
  pull_request:
    branches: [ "devel", "main" ]
    paths:
      - 'package.json'
      - 'tsconfig.base.json'
      - '.eslintrc.js'
      - 'backend/**'
  # Allowing to trigger this workflow manually
  workflow_dispatch:

jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        # See supported Node.js release schedule at https://nodejs.org/en/about/previous-releases
        node-version: 20.x
        cache: 'pnpm'
        cache-dependency-path: backend/pnpm-lock.yaml

    - name: Install common repo dependencies
      run: pnpm i --frozen-lockfile
      working-directory: .

    - name: Install backend dependencies
      run: pnpm i --frozen-lockfile

    - name: Generate Prisma types
      run: pnpm exec prisma generate

    - name: Lint the code
      run: pnpm lint

    - name: Build
      run: pnpm build

    - name: Run the tests
      run: pnpm test

  create-docker-image:
    name: Build and push Docker image to the GitHub Container registry
    if: ${{ github.event_name == 'push' }}
    needs: build-app
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_NAME: ${{ github.repository_owner }}/mafil-psq-server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=devel,enable=${{ github.ref_name == 'devel' }}
            type=raw,value={{date 'YYYY-MM-DD HH:mm:ss' tz='Europe/Prague'}}
            type=sha
          labels: |
            org.opencontainers.image.title=MAFIL - Proband Safety Questionnaire - server

      - name: Build and push the image to the GitHub Container registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
