name: CI - backend

on:
  push:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "backend", "main" ]
    paths:
      - 'backend/**'
  # We can manually trigger this workflow
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install common repo dependencies
      run: npm ci
      working-directory: .

    - name: Install backend dependencies
      run: npm ci

    - name: Lint the code
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Run the tests
      run: npm test

  push_to_docker_registry:
    name: Build and push Docker image to Docker Hub
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image to the GitHub Container registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: mafil-psq-server:${{ github.ref_name == 'main' && 'latest' || 'devel' }}
