name: CI - frontend

on:
  push:
    branches: [ "devel", "main" ]
    paths:
      - '.github/workflows/ci-frontend.yml'
      - 'docker-compose.devel.yml'
      - 'docker-compose.prod.yml'
      - 'frontend/**'
  pull_request:
    branches: [ "devel", "main" ]
    paths:
      - 'frontend/**'
  # Allowing to trigger this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install common repo dependencies
      run: npm ci
      working-directory: .

    - name: Install frontend dependencies
      run: npm ci

    - name: Lint the code
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Run the tests
      run: npm test

  create_docker_image:
    name: Build and push Docker image to the GitHub Container registry
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_NAME: ${{ github.repository_owner }}/mafil-psq-web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to the GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=devel,enable=${{ github.ref_name == 'devel' }}
            type=rew,value={{date 'YYYY-MM-DD HH:mm:ss' tz='Europe/Prague'}}
            type=sha
          labels: |
            org.opencontainers.image.title=MAFIL - Proband Safety Questionnaire - web

      - name: Build and push the image to the GitHub Container registry
        if: ${{ github.ref_name == 'devel' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          build-args: |
            JPM_CLIENT_ID=${{ secrets.JPM_CLIENT_ID }}
            APP_BAR_COLOR=${{ vars.DEV_APP_BAR_COLOR }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Build and push the image to the GitHub Container registry
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          build-args: |
            JPM_CLIENT_ID=${{ secrets.JPM_CLIENT_ID }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
